import { ReactNode } from "react";
import ThemeProviderClient from "../components/ThemeProviderClient";
import QueryProviderClient from "../components/QueryProviderClient";
import "./globals.css";

export const metadata = {
  title: "Chat App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <head />
      <body>
        <QueryProviderClient>
          <ThemeProviderClient>{children}</ThemeProviderClient>
        </QueryProviderClient>
      </body>
    </html>
  );
}
