import { ReactNode, Suspense } from "react";
import QueryProviderClient from "../components/QueryProviderClient";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { ThemeProvider } from "@mui/system";
import theme from "@/services/theme";
import RouteChangeHandler from "@/components/RouteChangeHandler";

export const metadata = {
  title: "Chathub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <head />
      <body>
        <AppRouterCacheProvider>
          <QueryProviderClient>
            <AuthProvider>
              <ThemeProvider theme={theme}>
                <Suspense fallback={<>Loading...</>}>
                  {children}
                  <RouteChangeHandler />
                </Suspense>
              </ThemeProvider>
            </AuthProvider>
          </QueryProviderClient>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
